package com.cultureoftech.easyexpensetracker.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.cultureoftech.easyexpensetracker.dao.Expense;
import com.cultureoftech.easyexpensetracker.dao.Payee;
import com.cultureoftech.easyexpensetracker.dao.ExpenseReport;

import com.cultureoftech.easyexpensetracker.dao.ExpenseDao;
import com.cultureoftech.easyexpensetracker.dao.PayeeDao;
import com.cultureoftech.easyexpensetracker.dao.ExpenseReportDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig expenseDaoConfig;
    private final DaoConfig payeeDaoConfig;
    private final DaoConfig expenseReportDaoConfig;

    private final ExpenseDao expenseDao;
    private final PayeeDao payeeDao;
    private final ExpenseReportDao expenseReportDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        expenseDaoConfig = daoConfigMap.get(ExpenseDao.class).clone();
        expenseDaoConfig.initIdentityScope(type);

        payeeDaoConfig = daoConfigMap.get(PayeeDao.class).clone();
        payeeDaoConfig.initIdentityScope(type);

        expenseReportDaoConfig = daoConfigMap.get(ExpenseReportDao.class).clone();
        expenseReportDaoConfig.initIdentityScope(type);

        expenseDao = new ExpenseDao(expenseDaoConfig, this);
        payeeDao = new PayeeDao(payeeDaoConfig, this);
        expenseReportDao = new ExpenseReportDao(expenseReportDaoConfig, this);

        registerDao(Expense.class, expenseDao);
        registerDao(Payee.class, payeeDao);
        registerDao(ExpenseReport.class, expenseReportDao);
    }
    
    public void clear() {
        expenseDaoConfig.getIdentityScope().clear();
        payeeDaoConfig.getIdentityScope().clear();
        expenseReportDaoConfig.getIdentityScope().clear();
    }

    public ExpenseDao getExpenseDao() {
        return expenseDao;
    }

    public PayeeDao getPayeeDao() {
        return payeeDao;
    }

    public ExpenseReportDao getExpenseReportDao() {
        return expenseReportDao;
    }

}
